# Generated by Django 5.2.7 on 2025-10-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='DEV.transaction')),
            ],
        ),
    ]
